# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3.8'
# docker-compose -f docker-compose.yml up -d
services:
  chatgpt-data-app:
    image: boom0730/chatgpt-data-app:1.4
    container_name: chatgpt-data-app
    ports:
      - "80:80"
    environment:
      - TZ=PRC
      - SERVER_PORT=80
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - THREAD_POOL_EXECUTOR_CONFIG_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_CONFIG_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_CONFIG_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_CONFIG_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_CONFIG_POLICY=CallerRunsPolicy
      - CHATGPT_SDK_CONFIG_API_HOST=https://pro-share-api.zcyai.com/
      - CHATGPT_SDK_CONFIG_API_KEY=sk-6tgWbt69i4PgYtAh546dE3251c35411d93A375D40c76F644
      - WX_CONFIG_ORIGINALID=gh_737a9f749590
      - WX_CONFIG_APPID=wxdc6c10561cbf6dc5
      - WX_CONFIG_TOKEN=boom730
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  chatgpt-web:
    container_name: chatgpt-web
    image: boom0730/chatgpt-web:1.4
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST_URL=http://116.198.244.169:80
    restart: always
networks:
  my-network:
    driver: bridge
