server:
  port: 8091

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://pro-share-aws-api.zcyai.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-xMfFDTpPdxPiJVbl5cD12543B71f4477B40b24D30a3bDf88

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_737a9f749590
    appid: wxdc6c10561cbf6dc5
    token: boom0730
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml